Script started on 2017年03月12日 (週日) 11時39分30秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m ./QBg++ -o QB QB.cppls[K git clone https://github.com/ya-sin/lab1.git<your github account>>/lab1.git[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[2Pwhoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd[7P./QBg++ -o QB QB.cppls[K git clone https://github.com/ya-sin/lab1.git<your github account>>/lab1.git[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[2Pwhoami; pwdgit config -l
user.email=luoyasin@gmail.com
user.name=ya-sin
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l[2Pwhoami; pwd[7P./QBg++ -o QB QB.cppls[K git clone https://github.com/ya-sin/lab1.git[1P
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月12日 (週日) 11時40分01秒
