Script started on 2017年03月12日 (週日) 12時28分36秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m g++ -o QB QB.cpp
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m ./QB
-1
please enter a number greater than 0
0
please enter a number greater than 0
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m 
Script done on 2017年03月12日 (週日) 12時29分03秒
